### ISSUE TITLE
Extended example

### ISSUE THREAD

**Issue by dbdimitrov** [AntoinePassemiers/PORTIA#1]
Hi @AntoinePassemiers,

I recently found your package and I'm interested in running it for a project of mine, particularly as it seems that you allow to whitelist entities (TFs in your case) and of course speed. However, I'm struggling with understanding and running the provided tutorial.

I assume that when you define an experiment the data should be an expression matrix, while the id is arbitrary. Yet, I am unable to run PORTIA (using your test text files).

Would be great if you can provide a self-contained tutorial - i.e. something that one could simply run from start to finish. For example, in a jupyter-notebook.

Thanks in advance.

**Comment by AntoinePassemiers** [comment]
Hello @dbdimitrov , my apologies, I am seeing this quite late. I could not run your notebook, as you only sent me the html output, and did not provide the input data.

In the following code example:
`dataset.add(pt.Experiment(exp_id, data))`,
`data` corresponds to a single observation, so it must be a list of expression values, or a numpy array of shape (n_genes,).
So in your case, you should extract each row (column?) of your pandas dataframe, and pass it to the add method individually.

In case you still struggle with the programming, another solution is to use the standalone script, for which I've made minimal working examples:
`python3 run.py test-data/dataset2.expression.txt --kos test-data/dataset2.kos.txt --tfs test-data/dataset2.tfs.txt --out test-data/out2.txt`

**Comment by dbdimitrov** [comment]
Hi @AntoinePassemiers,

Yeah, clarifying what data means was sufficient (noticed it in the readme after your suggestion). Thanks.

I simply cloned your repo and was using the data from test-data. Simply loading this and populating an instance of `dataset` would be useful as a tutorial (less likely to get confused as I did).

**Comment by dbdimitrov** [comment]
"data must be an iterable (list, NumPy array, etc)" was a bit vague to me, in reality it should be simply an iterable with vectors of samples/etc? :)
